### ISSUE TITLE
Create API method should return "201 Created" and not "200 OK"

### ISSUE THREAD

**Issue by iliafrenkel** [iliafrenkel/go-pb#1]
The `ApiServer.handleCreate` must return `201 Created` on success instead of `200 OK`. It should also update the `Location` header to contain the URL to the newly created paste.

Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201

And don't forget to update the tests.

**Comment by krishnaindani** [comment]
Is this open for work, I would like to explore if available?

**Comment by iliafrenkel** [comment]
Sure! Just take into account that the whole project is very much a work in progress and changes a lot. But by all means, give it a go ;-)

**Comment by iliafrenkel** [comment]
You can run `go test ./...` for testing.

**Comment by krishnaindani** [comment]
> You can run `go test ./...` for testing.

sounds good. Thanks

**Comment by krishnaindani** [comment]
I have one question when we return the `Location` header, is the `URL`(https://github.com/iliafrenkel/go-pb/blob/main/api/api.go#L22) the right method to get the location? Also, it looks like base62 encoded, does it needs to return in the same format?

**Comment by iliafrenkel** [comment]
I'm not sure I understand the question correctly... But I think the answer is Yes.
The `URL` is what you need (or will need) to get access to the paste: `https://example.com/p/<URL>`

**Comment by krishnaindani** [comment]
I mean in `Location` header we need to return the path URL. So we just return here the encoded URL, right? Is it making sense?

**Comment by iliafrenkel** [comment]
It should probably be `"/p/"+p.URL()` for now. Until I introduce the global BASE_URL or something similar.

**Comment by krishnaindani** [comment]
> It should probably be `"/p/"+p.URL()` for now. Until I introduce the global BASE_URL or something similar.

Isn't that will be handled in the app code?

**Comment by iliafrenkel** [comment]
Yes, you are absolutely right! I'm doing 10 things at once, hard to concentrate :-)
`p.URL()` is correct, the app will then construct the full path.

**Comment by krishnaindani** [comment]
happens to me all the time, will go with only returning the `p.URL()`. Thanks

**Comment by krishnaindani** [comment]
I have got the PR ready https://github.com/iliafrenkel/go-pb/pull/2
