### ISSUE TITLE
Cannot paste more than 10,240 characters.

### ISSUE THREAD

**Issue by davidnewhall** [iliafrenkel/go-pb#66]
**Describe the bug**
I cannot paste over 10,240 characters.

**To Reproduce**
Run the app and try to paste something large.

**Expected behaviour**
`WEB_MAX_BODY_SIZE` or `--web-max-body-size` properly controls the maximum paste size.

**Screenshots**
I cloned, ran `make build` (because `make` failed), then ran the app:
```
go-pb$ GOPB_DEBUG=true WEB_MAX_BODY_SIZE=6000000 build/go-pb --web-max-body-size=6000000
go-pb v0.0.9-alpha
2022/01/08 01:58:43.756 [INFO]  {cmd/main.go:84 main.main} Options: {Timeouts:{Shutdown:10s HTTPRead:15s HTTPWrite:15s HTTPIdle:1m0s} Web:{Proto:http Host:localhost Port:8080 LogFile: LogMode:production BrandName:Go PB BrandTagline:A nice and simple pastebin alternative that you can host yourself. Assets:./assets Templates:./templates BootstrapTheme:original Logo:bighead.svg MaxBodySize:6000000} DB:{Type:memory Connection:} Auth:{Secret: TokenDuration:5m0s CookieDuration:24h0m0s Issuer:go-pb URL:http://localhost:8080 GitHubCID: GitHubCSEC: GoogleCID: GoogleCSEC: TwitterCID: TwitterCSEC:} Debug:true LogFile:}
```
![Screen Shot 2022-01-08 at 2 03 28 AM](https://user-images.githubusercontent.com/2402929/148640168-49b519ac-b51a-43c9-8471-d3fdce662c0d.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser Safari
 - Version 15.2 (old)

Not sure what else to try.

**Comment by davidnewhall** [comment]
Never mind, I found this. https://github.com/iliafrenkel/go-pb/blob/main/templates/form.html#L9

**Comment by davidnewhall** [comment]
Okay, sorry I'm back. I bumped the limit (in both places) to `6000000` then attempted to paste a 5 MB (5242870 characters) log file.
```
2022/01/08 02:14:22.093 [INFO]  {lgr@v0.10.4/adaptor.go:16 lgr.(*Writer).Write} 127.0.0.1 - - [08/Jan/2022:02:14:22 -0800] "GET / HTTP/1.1" 200 30491 "http://127.0.0.1:8080/p/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
2022/01/08 02:14:28.770 [WARN]  {web/routes.go:143 web.(*Server).handlePostPaste} parsing form failed: http: request body too large
2022/01/08 02:14:28.771 [INFO]  {lgr@v0.10.4/adaptor.go:16 lgr.(*Writer).Write} 127.0.0.1 - - [08/Jan/2022:02:14:28 -0800] "POST /p/ HTTP/1.1" 400 8198 "http://127.0.0.1:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
```
![Screen Shot 2022-01-08 at 2 15 29 AM](https://user-images.githubusercontent.com/2402929/148640457-76289a42-701c-4e53-bfdd-dc3b587a994d.png)

Something between the _form limit_ and the _go limit_ it's mismatching the size, and truncating the POST body [here](https://github.com/iliafrenkel/go-pb/blob/main/src/web/routes.go#L141). I don't really think this is something you need to fix, just providing more data in case anyone else wants to deal with large files. I bumped the go limit to `100000000` (100Mb), and the paste worked.

So far, I'm quite impressed with the large-file-performance. Most apps suck. Well done on that!

**Comment by iliafrenkel** [comment]
Thank you @davidnewhall! The 10k limit was intentional. I've never thought of making another file sharing service.
But I agree, it should be configurable. And it will be, some time in the future. And the large volume testing will be done around the same time 😄. Thanks for your help, btw! I'm not ignoring you. I came back from a vacation a few days ago. I am trying to get back into the groove.

**Comment by davidnewhall** [comment]
> Thanks for your help, btw! I'm not ignoring you. 

No worries, take your time. If you're up for it, I have plenty more help to send your way.
